[2025-04-07T16:55:42.501+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-07T16:55:42.522+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_scraping_dag.scrape_amazon_task manual__2025-04-07T16:55:35.098821+00:00 [queued]>
[2025-04-07T16:55:42.537+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_scraping_dag.scrape_amazon_task manual__2025-04-07T16:55:35.098821+00:00 [queued]>
[2025-04-07T16:55:42.538+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-07T16:55:42.567+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): scrape_amazon_task> on 2025-04-07 16:55:35.098821+00:00
[2025-04-07T16:55:42.579+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=92) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-07T16:55:42.583+0000] {standard_task_runner.py:72} INFO - Started process 102 to run task
[2025-04-07T16:55:42.583+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'amazon_scraping_dag', 'scrape_amazon_task', 'manual__2025-04-07T16:55:35.098821+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/another_another_test.py', '--cfg-path', '/tmp/tmp5gbwzoka']
[2025-04-07T16:55:42.585+0000] {standard_task_runner.py:105} INFO - Job 71: Subtask scrape_amazon_task
[2025-04-07T16:55:42.668+0000] {task_command.py:467} INFO - Running <TaskInstance: amazon_scraping_dag.scrape_amazon_task manual__2025-04-07T16:55:35.098821+00:00 [running]> on host 13b4251b7529
[2025-04-07T16:55:42.819+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='amazon_scraping_dag' AIRFLOW_CTX_TASK_ID='scrape_amazon_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-07T16:55:35.098821+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-07T16:55:35.098821+00:00'
[2025-04-07T16:55:42.825+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-07T16:55:42.825+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-07T16:55:42.826+0000] {logging_mixin.py:190} INFO - Current task name:scrape_amazon_task state:running start_date:2025-04-07 16:55:42.524208+00:00
[2025-04-07T16:55:42.826+0000] {logging_mixin.py:190} INFO - Dag name:amazon_scraping_dag and current dag run status:running
[2025-04-07T16:55:42.827+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-07T16:55:42.853+0000] {another_another_test.py:285} INFO - Processing 1/15: Automotive/Car Care - https://www.amazon.com/s?bbn=2562090011&rh=i%3Aspecialty-aps%2Cn%3A2562090011%2Cn%3A%2115690151%2Cn%3A15718271&s=date-desc-rank&ref_=nav_em__nav_desktop_sa_intl_car_care_0_2_10_2
[2025-04-07T16:55:43.081+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2025-04-07T16:55:43.774+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-04-07T16:55:44.019+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-04-07T16:55:44.196+0000] {logger.py:11} INFO - There is no [linux64] chromedriver "135.0.7049.42" for browser google-chrome "135.0.7049" in cache
[2025-04-07T16:55:44.197+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-04-07T16:55:44.647+0000] {logger.py:11} INFO - WebDriver version 135.0.7049.42 selected
[2025-04-07T16:55:44.653+0000] {logger.py:11} INFO - Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.42/linux64/chromedriver-linux64.zip
[2025-04-07T16:55:44.654+0000] {logger.py:11} INFO - About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.42/linux64/chromedriver-linux64.zip
[2025-04-07T16:55:44.792+0000] {logger.py:11} INFO - Driver downloading response is 200
[2025-04-07T16:55:46.102+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-04-07T16:55:46.706+0000] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/135.0.7049.42]
[2025-04-07T16:55:51.990+0000] {another_another_test.py:80} INFO - Detected layout: tiles
[2025-04-07T16:55:52.057+0000] {another_another_test.py:261} ERROR - Error during scraping https://www.amazon.com/s?bbn=2562090011&rh=i%3Aspecialty-aps%2Cn%3A2562090011%2Cn%3A%2115690151%2Cn%3A15718271&s=date-desc-rank&ref_=nav_em__nav_desktop_sa_intl_car_care_0_2_10_2: cannot access local variable 'timestamp' where it is not associated with a value
[2025-04-07T16:55:52.221+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/another_another_test.py", line 245, in scrape
    self.save_to_csv(department, sub_department)
  File "/opt/airflow/dags/another_another_test.py", line 216, in save_to_csv
    output_dir = Path(f'/opt/airflow/csv/src_output/part1_{timestamp}')
                                                           ^^^^^^^^^
UnboundLocalError: cannot access local variable 'timestamp' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/another_another_test.py", line 289, in main
    scraper.scrape(url, department, sub_department)
  File "/opt/airflow/dags/another_another_test.py", line 262, in scrape
    self.save_to_csv(department, sub_department)  # Lưu dữ liệu trước khi thoát
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/another_another_test.py", line 216, in save_to_csv
    output_dir = Path(f'/opt/airflow/csv/src_output/part1_{timestamp}')
                                                           ^^^^^^^^^
UnboundLocalError: cannot access local variable 'timestamp' where it is not associated with a value
[2025-04-07T16:55:52.243+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-07T16:55:52.244+0000] {logging_mixin.py:190} INFO - Task start:2025-04-07 16:55:42.524208+00:00 end:2025-04-07 16:55:52.242640+00:00 duration:9.718432
[2025-04-07T16:55:52.245+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): scrape_amazon_task> dag:<DAG: amazon_scraping_dag> dagrun:<DagRun amazon_scraping_dag @ 2025-04-07 16:55:35.098821+00:00: manual__2025-04-07T16:55:35.098821+00:00, state:running, queued_at: 2025-04-07 16:55:35.117443+00:00. externally triggered: True>
[2025-04-07T16:55:52.245+0000] {logging_mixin.py:190} INFO - Failure caused by cannot access local variable 'timestamp' where it is not associated with a value
[2025-04-07T16:55:52.246+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=amazon_scraping_dag, task_id=scrape_amazon_task, run_id=manual__2025-04-07T16:55:35.098821+00:00, execution_date=20250407T165535, start_date=20250407T165542, end_date=20250407T165552
[2025-04-07T16:55:52.296+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-07T16:55:52.297+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 71 for task scrape_amazon_task (cannot access local variable 'timestamp' where it is not associated with a value; 102)
Traceback (most recent call last):
  File "/opt/airflow/dags/another_another_test.py", line 245, in scrape
    self.save_to_csv(department, sub_department)
  File "/opt/airflow/dags/another_another_test.py", line 216, in save_to_csv
    output_dir = Path(f'/opt/airflow/csv/src_output/part1_{timestamp}')
                                                           ^^^^^^^^^
UnboundLocalError: cannot access local variable 'timestamp' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/another_another_test.py", line 289, in main
    scraper.scrape(url, department, sub_department)
  File "/opt/airflow/dags/another_another_test.py", line 262, in scrape
    self.save_to_csv(department, sub_department)  # Lưu dữ liệu trước khi thoát
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/another_another_test.py", line 216, in save_to_csv
    output_dir = Path(f'/opt/airflow/csv/src_output/part1_{timestamp}')
                                                           ^^^^^^^^^
UnboundLocalError: cannot access local variable 'timestamp' where it is not associated with a value
[2025-04-07T16:55:52.351+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-07T16:55:52.378+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-07T16:55:52.383+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
